### ISSUE TITLE
Support for named parameter?

### ISSUE THREAD

**Issue by lockcole** [jkufner/flupdo#1]
The readme mentioned that named parameter is supported. But I cannot get it works. 
I searched in the code and found that all bindValue calls are made using $i which is parameter index.

**Comment by jkufner** [comment]
There are two expected ways to use Flupdo:
1. positional parameters:
   
   ```
   $pdoStmt = $q->select('y')->from('t')
       ->where('a = ?', $a)
       ->where('b = ?', $b)
       ->query();
   ```
2. named parameters:
   
   ```
   $pdoStmt = $q->select('y')->from('t')
       ->where('a = :A')
       ->where('b = :B')
       ->prepare();
   $pdoStmt->execute(array('A' => $a, 'B' => $b));
   ```

When query is build to be executed once, it is better to use the first approach. When it is going to be used multiple times, for example when inserting multiple rows, it is better to use the second approach.

Does this anwser your question?

**Comment by lockcole** [comment]
I see your point now. This answer my question. Thank you very much.
